# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac5d62bcc2990bff2dbe31a737cad5d46890ebe2ef7ed26e827708eda48822b62f38e53ef438f57f7cd756b7cd55fbc5ebfc580b4d81cdc2b0a876e4ef82f3d4

test:
  secret_key_base: 0221caf7a71e304302b1ee676b886fd223e52d5600d9f80ee311ffa7ec1f3468cdd452f64d9542eef8b7067177eb212e2ad4ea393facac7d99ceb4fe16bc0e6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
